
spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader

      server:
        webflux:
          routes:

            # ✅ USER SERVICE
            - id: user_service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10
                    key-resolver: "#{@userKeyResolver}"

            # ✅ ORDER SERVICE
            - id: order_service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 2
                    redis-rate-limiter.burstCapacity: 5
                    key-resolver: "#{@userKeyResolver}"

            # ✅ PAYMENT SERVICE
            - id: payment_service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payments/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 2
                    redis-rate-limiter.burstCapacity: 5
                    key-resolver: "#{@userKeyResolver}"

            # ✅ AUTH (NO RATE LIMIT — IMPORTANT)
            - id: auth_service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG
